### ISSUE TITLE
Setup kanban board

### ISSUE THREAD

**Issue by preciousuwhubetine** [preciousbetine/microverse-final-capstone-project#22]
There are five people on the team.
Here's the link to the [Github project](https://github.com/preciousbetine/microverse-final-capstone-project/projects/1).

Screenshot of kanban board:

![image](https://github.com/preciousbetine/microverse-final-capstone-project/assets/56425107/d81b350d-ed11-4bd5-95c3-504934ac26da)

**Comment by Meltrust** [comment]
Hi @preciousbetine,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks are assigned ✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] According to the project [requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md):

![image](https://github.com/preciousbetine/microverse-final-capstone-project/assets/57421823/8ebd5ddf-2472-455f-82f3-fa42a404bafc)

These are the pointings at the time of this review:

David-Lanzz 20
ilyassatlassi 18
Fahim-Khan-P 12
preciousbetine 25
SabiMantock 14

The pointings are too wide spread.  Please make it so nobody in the team has more than 5 points than any other.

That way, we will meet this particular requirement. 👍 

- [ ] Kindly, assign some points to this card:

![image](https://github.com/preciousbetine/microverse-final-capstone-project/assets/57421823/87841247-f6b9-451f-baf4-cea9dfe95d2d)

That way, we will meet the requirement that states that all cards need to have points. 👍 



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  
Good luck! 🎉 

## Highlights
- Successfully addressed review changes 👍 

## Optional suggestions
- [OPTIONAL] Consider adding labels to your issues, it makes it easier to filter by different types and gives another added level of differentiation among tasks (front-end vs back-end etc.)

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**Hope all is well, and that my comments were helpful. 😸**

Cheers and Happy coding!👏👏👏


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by preciousuwhubetine** [comment]
@mcrd25 Thanks for the suggestion. I will add labels to the issues.
